### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by YsenGrimm** [YsenGrimm/LongLongSnake#9]

**Comment by MWehrstedt** [comment]
Simples Menü schon erstellt, mit weiteren Quest kommt möglicherweise noch etwas dazu (zum Beispiel Levelauswahl)

**Comment by MWehrstedt** [comment]
Prototyp eines Menüs erstellt, Skalierung stimmt eventuell nicht richtig (vor allem auf mobilen Geräten), aber da arbeite ich dran.
